---
dist: trusty
language: python
python: "2.7"
before_install:
 - uname -a
 - sudo apt-get update -qq
 - sudo apt-get install -qq python-apt python-pycurl
 - ln -s ansible-siftrem ../siftrem
## FIXME! under travis, 'adding REMnux repository' fails whereas it works with kitchen...
# - sudo add-apt-repository ppa:remnux/stable -y
## http://www.webupd8.org/2016/03/fix-failed-to-fetch-google-chrome_3.html
 - sudo sed -i -e 's/deb http/deb [arch=amd64] http/' "/etc/apt/sources.list.d/google-chrome.list"
 - cat /etc/apt/sources.list
 - ls /etc/apt/sources.list.d/
install:
  - pip install ansible
  - ansible --version
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"
script:
  - "echo \"[test-kitchen]\nlocalhost\" > inventory"

# Check the role/playbook's syntax.
  - "ansible-playbook -i inventory --syntax-check test/integration/default/travis.yml"

# Run the role/playbook with ansible-playbook.
## some part of the install are greater than default 10min travis timeout
## https://docs.travis-ci.com/user/common-build-problems/#My-builds-are-timing-out
  - "ansible-playbook -i inventory --connection=local --sudo -vvvv test/integration/default/travis.yml"

## FIXME! https://github.com/travis-ci/travis-ci/issues/3810
# Run the role/playbook again, checking to make sure it's idempotent.
#  - "ansible-playbook -i inventory test/integration/default/travis.yml --connection=local --sudo | tee /tmp/idempotency.log | grep -q 'changed=0.*failed=0'  && (echo 'Idempotence test: pass' && exit 0)  || (echo 'Idempotence test: fail' && cat /tmp/idempotency.log && exit 1)"

