---

# remnux v6: /opt/remnux-rules/yara = http://yararules.com/
# https://github.com/1aN0rmus/Yara
# http://phishme.com/a-peek-inside-an-affiliates-malspam-operation-kovter-and-miurefboaxxe-infections/
# https://github.com/mikesxrs/Open-Source-YARA-rules-



